// SPDX-License-Identifier: GPL-3.0-or-later
// fl_crtadj.sv - CRT Adjust glue for the Namco System FL core (PATREON requirement).
//
// Wraps rtl/video/crt_adjust_mlab.sv (rmonic79, GPLv3, core-side variant: no sys/ edits) at the emu
// video boundary. The adjustments (H-Size / H-Position / V-Shift) move the picture CONTENT through a
// one-line ping-pong buffer while the sync signals stay native, so an analog CRT never loses lock.
//
// ---- Why there is no extra video clock here -----------------------------------------------------
// The SUPER22 wrapper (rtl/s22_crtadj.sv) had to move the emu video output onto a dedicated 3x pixel
// clock, because on that core CE_PIXEL was already 1 pulse per clk. System FL does not need that:
// CLK_VIDEO is the 50 MHz core clock `clk` and CE_PIXEL is a FRACTIONAL cadence generated by
// rtl/fl_video_timing.sv --
//
//     phase += 756 every clk;  ce_pixel = (phase + 756 >= 6250);  phase -= 6250 on a tick
//
// i.e. exactly 756/6250 pixels per clk = 6.048 MHz average, ~8.267 clk per pixel with +/-1 clk
// jitter. clk is therefore already ~8x the pixel rate and plays the role of s22's clk_v4 directly:
// `ce_pix` is this wrapper's pxl_cen (no CDC, no toggle synchroniser, no ce4 derivation).
//
// ---- The read cadence (rd_ce) -------------------------------------------------------------------
// s22 built rd_ce as "one pixel every (24 + hsize) EIGHTHS of clk_v4", which works only because
// clk_v4 is an exact integer multiple of the pixel rate. Here the native period is the non-integer
// ratio 6250/756, so the read side uses a second accumulator of the SAME fractional form, scaled by
// the H-Size factor:
//
//     read period  =  (HSTEPS + hsize)/HSTEPS  x  native pixel period
//                  =  (HSTEPS + hsize) * CE_DEN / (HSTEPS * CE_NUM)  clk
//
//     rd_acc += RD_INC (= CE_NUM * HSTEPS = 756*24 = 18144) every clk
//     rd_tick when rd_acc + RD_INC >= RD_THRESH (= CE_DEN * (HSTEPS + hsize) = 6250 * n)
//
// With hsize = 0: RD_THRESH/RD_INC = 150000/18144 = 6250/756 -- bit-exactly the native rate, so
// "CRT Adjust On, all values 0" reads at exactly the native average pixel rate and the fractional
// cadence is preserved end to end. H-Size then steps the period by 1/24 of a pixel per click
// (n = 8..39 => 0.33x .. 1.63x), the same resolution the SUPER22 core ships with.
//
// RD_THRESH is built from a 32-entry constant mux (one entry per H-Size value, each a compile-time
// CE_DEN*n product) so no multiplier / DSP block is inferred.
//
// The one wiring rule of the module is obeyed: rd_acc is reset on the RISE of the module's
// `hs_ref_out`, NOT on the raw HSync, so the read rate and the module's internal read counter
// restart on the same edge. (In HPOS_CONTENTSHIFT mode hs_ref_out == the native HSync, but the rule
// is kept so HPOS_MODE can be flipped without re-deriving the glue.)
//
// ---- Sync polarity ------------------------------------------------------------------------------
// System FL's hsync/vsync are ACTIVE LOW (fl_video_timing: hsync = !(x>=304 && x<336)). The module
// only ever uses the RISING edge of hs_in as its once-per-line reference; with active-low sync that
// edge lands at x=336, inside horizontal blanking and after the active window (x < 288), which is
// exactly where the line-buffer bank must flip. Polarity is otherwise pass-through.
//
// ---- de_osd -------------------------------------------------------------------------------------
// VGA_DE rises at the NATIVE active start (so the MiSTer OSD stays centred while H-Position slides
// the picture) and falls with the ADJUSTED active end. Unlike s22_crtadj the rise is taken on the
// READ timeline rather than in native time -- see the comment at the de_osd logic below; in native
// time a shrink would lose the left edge of the picture.
//
// ---- Range of the controls (MEASURED, sim/crtadj.cpp) -----------------------------------------------
// The active area is 288 of 384 columns and the picture starts 48 columns after the sync edge, so
// there is room for 336 output columns per line. H-Size can therefore shrink without limit (all 288
// columns always survive) but only ENLARGE to about +3 (1.125x) before the right edge runs past the
// end of the line; H-Position keeps all 288 columns up to about +-40.
//
// ---- OSD (status[59:42], identical layout to SUPER22) -------------------------------------------
//   cfg[0]     = status[42]      CRT Adjust On/Off
//   cfg[5:1]   = status[47:43]   H-Size      signed 5-bit (0..+15, then -16..-1)
//   cfg[12:6]  = status[54:48]   H-Position  0..48 = +0..+48, 49..96 = -48..-1
//   cfg[17:13] = status[59:55]   V-Shift     signed 5-bit (0..+15, then -16..-1)
//
// ---- Off path -----------------------------------------------------------------------------------
// With CRT Adjust Off the outputs are the native picture/syncs re-registered once on ce_pix and
// CE_PIXEL = ce_pix: a single fixed pixel of pipeline delay applied equally to RGB, HS, VS and DE.
// The line buffer is not in the path and no colour bits are dropped.
module fl_crtadj #(
	parameter integer HTOTAL   = 384,   // System FL line length in pixels (fl_video_timing)
	parameter integer VTOTAL   = 264,   // System FL frame height in lines
	parameter integer CE_NUM   = 756,   // native ce_pix numerator   (fl_video_timing)
	parameter integer CE_DEN   = 6250,  // native ce_pix denominator (fl_video_timing)
	parameter integer HSTEPS   = 24,    // H-Size resolution: one click = 1/HSTEPS of a pixel period
	parameter integer DE_LEAD  = 1,     // read-counter offset from hb1 to the DE rise (calibrated)
	parameter         USE_MLAB = 1      // 1 = line buffer in MLABs (System FL: 549/553 M10K taken)
)(
	input  wire        clk,             // CLK_VIDEO (50 MHz core clock)
	input  wire        ce_pix,          // native pixel clock enable (fractional cadence)

	input  wire [7:0]  r, g, b,         // native picture, aligned with de/hs/vs
	input  wire        hs, vs,          // native syncs (active low on System FL)
	input  wire        de,              // native data enable (x < 288 && y < 224)
	input  wire        vb,              // native VERTICAL blank only (y >= 224)

	input  wire [17:0] cfg,             // status[59:42]

	output wire [7:0]  vga_r, vga_g, vga_b,
	output wire        vga_hs, vga_vs, vga_de,
	output wire        ce_pixel
);
	// ---- input pipeline (this IS the Off/bypass path) ----
	reg [7:0] v_r = 8'd0, v_g = 8'd0, v_b = 8'd0;
	reg       v_hs = 1'b1, v_vs = 1'b1, v_de = 1'b0, v_vb = 1'b0;
	always @(posedge clk) if (ce_pix) begin
		v_r <= r; v_g <= g; v_b <= b;
		v_hs <= hs; v_vs <= vs; v_de <= de; v_vb <= vb;
	end
	wire v_hb = ~v_de;   // "not active" (horizontal OR vertical), what crt_adjust wants on hb_in

	// ---- OSD decode (registered on ce_pix) ----
	reg              crt_on  = 1'b0;
	reg signed [4:0] hsize_s = 5'sd0;
	reg        [6:0] hpos_d  = 7'd0;
	reg signed [5:0] vshift_off = 6'sd0;
	always @(posedge clk) if (ce_pix) begin
		crt_on     <= cfg[0];
		hsize_s    <= $signed(cfg[5:1]);
		hpos_d     <= cfg[12:6];
		vshift_off <= $signed({cfg[17], cfg[17:13]});
	end
	wire signed [8:0] hpos_off = (hpos_d <= 7'd48) ? $signed({2'b0, hpos_d})
	                                               : ($signed({2'b0, hpos_d}) - 9'sd97);

	// ---- read clock enable: fractional cadence scaled by H-Size, reset on hs_ref rise ----
	localparam integer RD_INC  = CE_NUM * HSTEPS;                 // 18144
	localparam integer ACC_MAX = CE_DEN * (HSTEPS + 16) + RD_INC; // 268144
	localparam integer ACCW    = $clog2(ACC_MAX + 1);             // 19
	localparam integer AW      = 11;                              // matches crt_adjust's wrp/rdcnt
	/* verilator lint_off WIDTHTRUNC */
	localparam [AW-1:0] DE_LEAD_V = DE_LEAD;
	/* verilator lint_on WIDTHTRUNC */

	wire hs_ref;
	reg  hs_ref_d = 1'b1;
	always @(posedge clk) hs_ref_d <= hs_ref;
	wire hs_ref_rise = hs_ref & ~hs_ref_d;

	// RD_THRESH = CE_DEN * (HSTEPS + hsize). hsize is a 5-bit two's-complement OSD value, so the
	// 32 possible thresholds are compile-time constants: a 32:1 constant mux, never a multiplier.
	wire [4:0] hsize_u = hsize_s[4:0];
	reg  [ACCW-1:0] rd_thresh;
	integer k, thr_i;
	always @* begin
		thr_i = HSTEPS * CE_DEN;
		for (k = 0; k < 32; k = k + 1)
			if (hsize_u == k[4:0])
				thr_i = ((k < 16) ? (HSTEPS + k) : (HSTEPS + k - 32)) * CE_DEN;
		rd_thresh = thr_i[ACCW-1:0];
	end

	/* verilator lint_off WIDTHTRUNC */
	localparam [ACCW:0] RD_INC_V = CE_NUM * HSTEPS;   // 18144, fits in ACCW+1 = 20 bits
	/* verilator lint_on WIDTHTRUNC */
	reg  [ACCW-1:0] rd_acc = {ACCW{1'b0}};
	wire [ACCW:0]   rd_sum  = {1'b0, rd_acc} + RD_INC_V;
	wire [ACCW:0]   rd_next = rd_sum - {1'b0, rd_thresh};
	wire            rd_hit  = (rd_sum >= {1'b0, rd_thresh});
	always @(posedge clk) begin
		if      (hs_ref_rise) rd_acc <= {ACCW{1'b0}};
		else if (rd_hit)      rd_acc <= rd_next[ACCW-1:0];
		else                  rd_acc <= rd_sum[ACCW-1:0];
	end
	wire rd_ce = crt_on ? rd_hit : ce_pix;

	// ---- the module ----
	wire [7:0] str_r, str_g, str_b;
	wire       str_hs, str_vs, str_hb, str_vb;
	generate if (USE_MLAB) begin : g_mlab
		crt_adjust_mlab #(.VTOTAL(VTOTAL), .HTOTAL(HTOTAL), .HPOS_MODE(1)) u_crt (
			.clk(clk), .pxl_cen(ce_pix), .pxl2_cen(rd_ce), .active(crt_on),
			.hsize(hsize_s), .hoffset(hpos_off), .voffset(vshift_off),
			.r_in(v_r), .g_in(v_g), .b_in(v_b),
			.hs_in(v_hs), .vs_in(v_vs), .hb_in(v_hb), .vb_in(v_vb),
			.r_out(str_r), .g_out(str_g), .b_out(str_b),
			.hs_out(str_hs), .vs_out(str_vs), .hb_out(str_hb), .vb_out(str_vb),
			.hs_ref_out(hs_ref));
	end else begin : g_m10k
		crt_adjust #(.VTOTAL(VTOTAL), .HTOTAL(HTOTAL), .HPOS_MODE(1)) u_crt (
			.clk(clk), .pxl_cen(ce_pix), .pxl2_cen(rd_ce), .active(crt_on),
			.hsize(hsize_s), .hoffset(hpos_off), .voffset(vshift_off),
			.r_in(v_r), .g_in(v_g), .b_in(v_b),
			.hs_in(v_hs), .vs_in(v_vs), .hb_in(v_hb), .vb_in(v_vb),
			.r_out(str_r), .g_out(str_g), .b_out(str_b),
			.hs_out(str_hs), .vs_out(str_vs), .hb_out(str_hb), .vb_out(str_vb),
			.hs_ref_out(hs_ref));
	end endgenerate

	// ---- DE: rises at the NATIVE active start, falls with the adjusted active end --------------
	// s22_crtadj raises de_osd straight off the native (write-rate) active start. That is exact
	// there because clk_v4 is an integer 3x of the pixel clock AND base == 1 native pixel, so the
	// native start and the read counter never drift apart. Neither holds here: with H-Size != 0 the
	// read side runs at a different rate, so by the time the native active start comes round in
	// TIME the read counter is already tens of columns into the picture -- a shrink would lose the
	// whole left edge (MEASURED: H-Size -12 emitted only 238 of 288 columns that way).
	//
	// So the anchor is the same native active start, just expressed on the READ timeline: rise when
	// the read counter reaches the captured native active start hb1 (the position H-Position is
	// measured from), i.e. exactly where the picture would be with H-Position 0. H-Position then
	// still slides the content inside a DE window whose rise does NOT move -- the property that
	// keeps the MiSTer OSD centred -- while H-Size keeps the whole picture.
	//
	// wrp/hb1/rdc below replicate the module's own counters bit-for-bit (same reset edges, same
	// pre-increment capture), which is ~25 flops; DE_LEAD then matches the module's 2-stage output
	// pipeline so the first DE pixel IS source column 0 (calibrated in sim/crtadj.cpp).
	reg        hs_pix_d = 1'b1;                 // v_hs delayed one ce_pix (module's hs_ref_d1)
	reg        lhb_l    = 1'b0;
	reg [AW-1:0] wrp = {AW{1'b0}}, hb1 = {AW{1'b0}};
	always @(posedge clk) if (ce_pix) begin
		hs_pix_d <= v_hs;
		lhb_l    <= v_de;
		if (v_hs & ~hs_pix_d) wrp <= {AW{1'b0}};
		else                  wrp <= wrp + 1'b1;
		if (v_de & ~lhb_l)    hb1 <= wrp;
	end
	reg rd_pend = 1'b0;
	always @(posedge clk) begin
		if      (hs_ref_rise) rd_pend <= 1'b1;
		else if (rd_ce)       rd_pend <= 1'b0;
	end
	reg [AW-1:0] rdc = {AW{1'b0}};
	always @(posedge clk) if (rd_ce) rdc <= rd_pend ? {AW{1'b0}} : rdc + 1'b1;
	// Vertical blank, sampled exactly like the module's vb_line/vb_active pair.
	reg vb_line = 1'b0, vb_act = 1'b0;
	always @(posedge clk) if (hs_ref_rise) begin vb_line <= v_vb; vb_act <= vb_line; end

	wire str_active = ~str_hb;
	reg  str_active_d = 1'b0;
	always @(posedge clk) if (rd_ce) str_active_d <= str_active;
	wire str_fall = str_active_d & ~str_active;

	reg  de_hold = 1'b0;                        // DE already raised on this line
	// ~rd_pend skips the read tick that ZEROES rdc: on that tick rdc still holds the previous
	// line's (large) value and would fire de_set at once.
	wire de_set  = rd_ce & ~rd_pend & ~de_hold & ~vb_act & (rdc >= (hb1 + DE_LEAD_V));
	always @(posedge clk) begin
		if      (hs_ref_rise) de_hold <= 1'b0;
		else if (de_set)      de_hold <= 1'b1;
	end
	reg  de_osd = 1'b0;
	always @(posedge clk) begin
		if      (hs_ref_rise) de_osd <= 1'b0;   // DE always drops at the sync edge
		else if (de_set)      de_osd <= 1'b1;
		else if (str_fall)    de_osd <= 1'b0;
	end

	// ---- outputs ----
	assign vga_r    = crt_on ? str_r  : v_r;
	assign vga_g    = crt_on ? str_g  : v_g;
	assign vga_b    = crt_on ? str_b  : v_b;
	assign vga_hs   = crt_on ? str_hs : v_hs;
	assign vga_vs   = crt_on ? str_vs : v_vs;
	assign vga_de   = crt_on ? de_osd : v_de;
	assign ce_pixel = rd_ce;
endmodule
