// generated by tools/gen_pause_assets.py from pause_src/pause.txt (sha256 ee933dfb062034c0) - do not edit
localparam [6:0]  TEXT_LOOP   = 7'd46;   // 42 credit lines + 4-line gap
localparam [10:0] SCROLL_WRAP = 11'd736;  // TEXT_LOOP x 16 px
